# Generated by Django 5.2 on 2025-04-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='category',
            field=models.CharField(choices=[('positive', 'Позитивные'), ('neutral', 'Нейтральные'), ('negative', 'Негативные')], default='neutral', max_length=10),
        ),
    ]
